### ISSUE TITLE
Copy contributing.md to end of README

### ISSUE THREAD

**Issue by mattjegan** [mattjegan/rancat#23]
Copy the contents of `docs/contributing.md` into the end of `README.md` as info about contributing should be on the main page on github.

**Comment by taml** [comment]
Hey @mattjegan I'd like to take this one up if that's ok!

**Comment by mattjegan** [comment]
@taml No worries, just submit a PR when you're ready 😄  thanks for the help.

**Comment by taml** [comment]
Thanks! I've just submitted the PR!
