### ISSUE TITLE
tech project name generator option

### ISSUE THREAD

**Issue by cupOJoseph** [mattjegan/rancat#26]
Have a boolean, default to false, that checks if you're generating project names.

If you are generating project names replace parts in words that have "*it" with "bit".  Add -o to the end of words that end in to consonants or replace final vowel with o. Replace [H,P,C,K,T]-[AP,AC,AQ,Ak,AT] with Hack.

Ex: 
Sphere -> Sphero
Capital -> [Hackital](http://hackital.com/)

I will work on this shortly if @mattjegan would add it.

**Comment by mattjegan** [comment]
This sounds like it could be pretty cool, it's probably best to add it in as a conversion method in [conversions.py](https://github.com/mattjegan/rancat/blob/master/rancat/conversions.py)

**Comment by cupOJoseph** [comment]
Dope, I probably won't get to it until the weekend or early next week.

**Comment by mattjegan** [comment]
No worries, please remember to include tests 😄

**Comment by mattjegan** [comment]
After reviewing PR #30 I'm no longer confident I like this feature and hence am closing this issue for the time being.
