### ISSUE TITLE
Have a default set of inputs from lorem ipsum text.

### ISSUE THREAD

**Issue by hewhomustnotbenamed** [mattjegan/rancat#29]
Can use a switch --use-default-text to load some text from lorem ipsum so as to get a quick combination of random words.

Also maybe text could be loaded from url instead of just static files.

**Comment by mattjegan** [comment]
Yeah, I think this could be a good use case. Would you like to work on this? If so, please submit a PR for the `--use-default-text` implementation and then another for any url features since that could get tricky 😄

**Comment by hewhomustnotbenamed** [comment]
Sure!! Can you assign this issue to me?

**Comment by mattjegan** [comment]
All done, you're good to go 😄

**Comment by mattjegan** [comment]
Hey @hewhomustnotbenamed , are you still happy to do this?

**Comment by mattjegan** [comment]
I'm going to label this as help wanted in case anyone wants to pick it up

**Comment by the-c0d3r** [comment]
I would like to help with this enhancement. I'm not clear if I should setup a argument handling using `--use-default-text` or just write another method inside the RanCat class? And how to store a passage of "Lorem ipsum" in a file or as a variable? Please bear with me since I'm quite new to writing modular approach.

**Comment by mattjegan** [comment]
Hey, thanks for reaching out. I would probably suggest adding a new argparse argument `--use-default-text` which would set the source files as 2 lorem ipsum files which you can store in a new folder `rancat/assets/`

**Comment by the-c0d3r** [comment]
I am sorry for replying so late. I was waiting for the email notification but I didn't catch that. 

I have a few questions. This project is supposed to work as a module to be imported, not as a stand-alone program is it not? As I understand it there is no argument handling for code working as a module. Can you please clarify? I would really like to contribute in this.

**Comment by mattjegan** [comment]
Ahh I'm so sorry, I must've written this late at night and been confused with another project. You are completely right, **Rancat is imported as a python module** 

In such case I recommend implementing something like `Rancat.load_default()` which would pull from files located in `rancat/assets/`

Let me know if you get stuck.

**Comment by the-c0d3r** [comment]
I have created a pull request for this feature. I don't know if I did it correctly or not. Please feel free to comment on my pull request.
