### ISSUE TITLE
Allow urls to be used as a source for the generator.

### ISSUE THREAD

**Issue by mattjegan** [mattjegan/rancat#31]
As discussed here #29 

I will provide more info if needed.

**Comment by ashishkg0022** [comment]
hello, @mattjegan  I will like to work on this . can you provide some more detailed
 info about it?

**Comment by mattjegan** [comment]
Hey @ashishkg0022 sorry I didn't see this earlier, I imagine we would probably want to treat whatever the url is, as 1 entry per line. So to get the list needed for the generator we would go something like:

```python
import requests

page = requests.get('theUrlHere.com')
entries = [line for line in page]
```

This way, a user can provide a link to a raw .txt file for example and use that rather than having to have the file locally.

I would suggest implementing this in the `Rancat.load` method and detecting whether it is a url there and then handling it as such.
